name: sliceoptim
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scikit-optimize>=0.8
  - pytest>=6.2
  - pytest-cov>=2.12
  - pandas>=1.3
  - numpy>=1.21
  - tinydb>=4.4
  - sphinx>=4.1
  - sphinx_rtd_theme>=0.5
  - m2r2>=0.3
  - black>=21
